default:
  navigation:
    - title: Accueil
      subtitle: Categories
      url: /
      items:
        - :title: Agriculture
          :url: /t/agriculture
        - :title: Elevage
          :url: /t/elevage
        - :title: Electronique
          :url: /t/informatiques
        - :title: Vêtements
          :url: /t/clothes
    - title: Agriculture
      subtitle: Categories
      url: /t/agriculture
      items:
        - :title: Arachides
          :url: /t/agriculture/arachides
        - :title: Maïs
          :url: /t/agriculture/mais
        - :title: Piments
          :url: /t/agriculture/piments
      promo_banners:
        - subtitle: Special Ramadan
          title: Ramadan 2021
          url: /t/special-ramadan/ramadan-2021
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Offre Speciale
          title: Obtenez 30% de reduction
          url: /t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Elevage
      subtitle: Categories
      url: /t/elevage
      items:
        - :title: Poulets
          :url: /t/elevage/poulets
        - :title: Moutons
          :url: /t/elevage/moutons
        - :title: Boeufs
          :url: /t/elevage/boeufs
      promo_banners:
        - subtitle: Special Ramadan
          title: Ramadan 2021
          url: /t/special-ramadan/ramadan-2021
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Offre Speciale
          title: Obtenez 30% de reduction
          url: /t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Electronique
      subtitle: Categories
      url: /t/informatiques
      items:
        - :title: Smartphones
          :url: /t/informatiques/smartphones
        - :title: Electromenager
          :url: /t/informatiques/electromenager
        - :title: Ordinateurs
          :url: /t/informatiques/ordinateurs
      promo_banners:
        - subtitle: Special Ramadan
          title: Ramadan 2021
          url: /t/special-ramadan/ramadan-2021
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Offre Speciale
          title: Obtenez 30% de reduction
          url: /t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Vêtements
      subtitle: Categories
      url: /t/clothes
      items:
        - :title: Tops
          :url: /t/clothes/tops
        - :title: Sweatshirts
          :url: /t/clothes/sweatshirts
        - :title: Bazin
          :url: /t/clothes/bazin
      promo_banners:
        - subtitle: Nouvelle collection
          title: Ete 2021
          url: /t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Offres speciales
          title: Get up to 30% off
          url: /t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-third-category.jpg'
fr:
  navigation:
    - title: Acceuil
      subtitle: Categories
      url: /
      items:
        - :title: Agriculture
          :url: /t/agriculture
        - :title: Elevage
          :url: /t/elevage
        - :title: Electronique
          :url: /t/informatiques
        - :title: Vêtements
          :url: /t/clothes
    - title: Agriculture
      subtitle: Categories
      url: /t/agriculture
      items:
        - :title: Arachides
          :url: /t/agriculture/arachides
        - :title: Maïs
          :url: /t/agriculture/mais
        - :title: Piments
          :url: /t/agriculture/piments
      promo_banners:
        - subtitle: Special Ramadan
          title: Ramadan 2021
          url: /t/special-ramadan/ramadan-2021
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Offre Speciale
          title: Obtenez 30% de reduction
          url: /t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Elevage
      subtitle: Categories
      url: /t/elevage
      items:
        - :title: Poulets
          :url: /t/elevage/poulets
        - :title: Moutons
          :url: /t/elevage/moutons
        - :title: Boeufs
          :url: /t/elevage/boeufs
      promo_banners:
        - subtitle: Special Ramadan
          title: Ramadan 2021
          url: /t/special-ramadan/ramadan-2021
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Offre Speciale
          title: Obtenez 30% de reduction
          url: /t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Electronique
      subtitle: Categories
      url: /t/informatiques
      items:
        - :title: Smartphones
          :url: /t/informatiques/smartphones
        - :title: Electromenager
          :url: /t/informatiques/electromenager
        - :title: Ordinateurs
          :url: /t/informatiques/ordinateurs
      promo_banners:
        - subtitle: Special Ramadan
          title: Ramadan 2021
          url: /t/special-ramadan/ramadan-2021
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Offre Speciale
          title: Obtenez 30% de reduction
          url: /t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Vêtements
      subtitle: Categories
      url: /t/clothes
      items:
        - :title: Tops
          :url: /t/clothes/tops
        - :title: Sweatshirts
          :url: /t/clothes/sweatshirts
        - :title: Bazin
          :url: /t/clothes/bazin
      promo_banners:
        - subtitle: Nouvelle collection
          title: Ete 2021
          url: /t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Offres speciales
          title: Get up to 30% off
          url: /t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-third-category.jpg'